### ISSUE TITLE
hi!good work,but i want to know where is the  bdd100k_labels_images_%s.json?

### ISSUE THREAD

**Issue by tianyuluan** [tranleanh/MobileNets-SSD#1]

**Comment by tranleanh** [comment]
Hi,
Those are json label files, you should download them from the official site of the dataset: https://bdd-data.berkeley.edu/
Then extract it and you can get these files:
bdd100k_labels_images_train.json
bdd100k_labels_images_val.json

**Comment by tianyuluan** [comment]
Why is the annotation file in the BDD dataset I downloaded a picture corresponding to a. JSON file? Are these two. JSON files that you mentioned is the total annotation file or a label index file？


发自我的iPhone

------------------ Original ------------------

**Comment by tranleanh** [comment]
Each json file includes all anotations for training or validation. So we should have 2 json files. But after converting to VOC format, each image will have only one corresponding xml file.

**Comment by tianyuluan** [comment]
ok！i know.thank you very much.


发自我的iPhone

------------------ Original ------------------

**Comment by NiranjanRavi1993** [comment]
Hi @tranleanh ,
     I have downloaded the 100K images but I can't find the **bdd100k_labels_images_train.json
bdd100k_labels_images_val.json** files. In this link https://bdd-data.berkeley.edu/,

I tried to download the Detection_2020_labels but got these files det_train.json and det_val.json. Are they the required files? 
Any inputs will be helpful. 

Regards
Niranjan

**Comment by tranleanh** [comment]
They should be there in the dataset if you downloaded the proper dataset.

Otherwise, the authors might change the file names.

You can try to look inside those files.

Best,
LA Tran
