### ISSUE TITLE
Detect Objects: 0.

### ISSUE THREAD

**Issue by Royee-Lyu** [tranleanh/MobileNets-SSD#2]
Why Detect Objects: 0. when testing? 
I only train mb1-ssd on VOC2007 datasets, should I also pre-processing bdd2voc.py?

![851052d3ba67a575eaccb25590f217d](https://user-images.githubusercontent.com/71477081/99609382-bce4f480-2a4a-11eb-98ec-cddf882dc2e4.png)

**Comment by tranleanh** [comment]
If you test with VOC dataset, you do not need to do any preprocessing.

You should try to decrease the confidence threshold at [ssd_test_img.py](https://github.com/tranleanh/mobilenets-ssd-pytorch/blob/f4e817618a2b602ea06efe72f7486df990ff7f57/ssd_test_img.py#L84). For instance: 0.4 -> 0.2

**Comment by Royee-Lyu** [comment]
Thank you! I try to increase epoch number to 200 and then success
