### ISSUE TITLE
Resume training: always from epoch 0.

### ISSUE THREAD

**Issue by Royee-Lyu** [tranleanh/MobileNets-SSD#3]
I train MobileNet-SSD (VOC),but I can't resume training. It always resumes training from epoch 0. What's the reason?

**Comment by tranleanh** [comment]
1. Make sure that you run exactly the command that I wrote in README section. 
2. Your problem may not be exactly a problem. Because when we resume training, the epoch counting starts from 0. You should look at the loss value.
