### ISSUE TITLE
Do you know where is mb1-ssd-Epoch-105-Loss-inf.pth ?Thank you so much.

### ISSUE THREAD

**Issue by Eazin-g** [tranleanh/MobileNets-SSD#5]

**Comment by Eazin-g** [comment]
And do you konw where is mb2-ssd-lite-Epoch-35-Loss-inf.pth? I didn't find them when run ssd_test_img.py and ssd_test_vedio.py. Thank you so much.

**Comment by tranleanh** [comment]
Hi,

You need to train your model and put the model path to those scripts.
