### ISSUE TITLE
Index for mobilenetSSD

### ISSUE THREAD

**Issue by Kevin-Wei-Chih** [tranleanh/MobileNets-SSD#6]
Do you have mAP index for mobilenetSSD when training mobilenetSSD?
Thank yor for sharing!

**Comment by tranleanh** [comment]
I trained this mobilenet-ssd on my customized dataset, so it can not be used as a benchmark, that's why I do not show it here.

**Comment by Kevin-Wei-Chih** [comment]
Thanks for your response.
Excuses me.
Can I ask where can I download the VOC dataset as you provided in the README.md(like the structure of data path thay you mentioned)?
Because in my own VOC dataset,I don't have the VOCdevkit/test floder.

**Comment by tranleanh** [comment]
FYI.

https://pjreddie.com/projects/pascal-voc-dataset-mirror/

Best.
